sudo: required
service: 
  - docker

# test again thats why build with  Dockerfile.dev
before_install:
  - docker build -t kgr/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true kgr/react-test npm test

after_success:
  - docker build -t kgrdocker/multi-client ./client
  - docker build -t kgrdocker/multi-nginx ./nginx
  - docker build -t kgrdocker/multi-server ./server
  - docker build -t kgrdocker/multi-worker ./worker
  # login into docker cli 
  # (travis ci / project / more options / settings / env variables)
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # upload images to docker hub
  - docker push kgrdocker/multi-client
  - docker push kgrdocker/multi-nginx
  - docker push kgrdocker/multi-server
  - docker push kgrdocker/multi-worker



 

